apiVersion: v1
kind: Service
metadata:
  name: orders-api-ClusterIP
  labels:
    app: orders-api
spec:
  type: ClusterIP
  selector:
    app: orders-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000